### ISSUE TITLE
[BUG] Settings.yml is having issues when deploying.

### ISSUE THREAD

**Issue by ghost** [Ruby-Network/ruby#11]
**Note: for support questions, please use our [Discord](https://discord.gg/HUKuWtXwS5)**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [ ] bug report
  - [  ] feature request
  - [  ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**
When changing ANY variable within the settings.yml in config the instance will fail to deploy with this error code: `[1060] Puma starting in cluster mode...
[1060] * Puma version: 6.3.1 (ruby 3.2.1-p31) ("Mugi No Toki Itaru")
[1060] *  Min threads: 0
[1060] *  Max threads: 5
[1060] *  Environment: production
[1060] *   Master PID: 1060
[1060] *      Workers: 16
[1060] *     Restarts: (✔) hot (✖) phased
[1060] * Preloading application
Verbose logging is disabled
{:mainURL=>["must have no url"], :username=>["the username must NOT be \"ruby\""], :password=>["the password must NOT be \"ruby\""]}
Please fix the above errors and restart the server.
[1060] ! Unable to load application: SystemExit: exit`

* **What is the current behavior?**

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
Just change any value in the settings.yml and deploy.

* **What is the expected behavior?**
A successful deploy.

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**
  
  - Version: 2.0.0-beta.X
  - Browser: [all | Chrome XX  | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  - Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]
  Chrome

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

Hosting on gitpod.io. It works well without any settings being changed

**Comment by MotorTruck1221** [comment]
Ok, so this looks like you are trying to host a private instance. Am I correct @Bmbay10 ?

**Comment by MotorTruck1221** [comment]
If so, please reference the [docs](https://github.com/Ruby-Network/ruby/blob/main/docs/private.md)

**Comment by MotorTruck1221** [comment]
If using a private instance the Password/Username *cannot* be "ruby" and the main URL *must* be "NA"

**Comment by MotorTruck1221** [comment]
I am closing this issue
