### ISSUE TITLE
DISCORD

### ISSUE THREAD

**Issue by Anon10104** [Ruby-Network/ruby#19]
**Note: for support questions, please use our [Discord](https://discord.gg/HUKuWtXwS5)**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [  ] bug report
  - [  ] feature request
  - [ x ] support request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

not to be rude but i want a working discord link so I can actually get support bc https://discord.gg/HUKuWtXwS5 doesnt work

* **What is the current behavior?**

I cant find your discord anywhere and your link it doesn't work

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

* **What is the expected behavior?**

a working link

* **What is the motivation / use case for changing the behavior?**

mabye more people join your server assuming there is one 

* **Please tell us about your environment:**
  
  - Version: 2.0.0-beta.X
  - Browser: [ **all** | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  - Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart]

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by MotorTruck1221** [comment]
I'm not quite sure where that link is even coming from...

https://discord.com/invite/rbWVGBfuwV will work.

**Comment by Anon10104** [comment]
thank you much appreciated i got that link [HUKuWtXwS5] from the note for support on the issue format
