### ISSUE TITLE
[BUG/Feature Request]

### ISSUE THREAD

**Issue by The-Rock-21** [Ruby-Network/ruby#21]
**Note: for support questions, please use our [Discord](https://discord.gg/HUKuWtXwS5)**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [ Yes ] bug report
* **Do you want to request a *feature* or report a *bug*?**

* **What is the current behavior?**
This is really common and whenever I use it in hopes of it working, it keeps saying bad gateway.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).
Go to website
See bad gateway 
![Screenshot 2023-11-14 1 20 05 PM](https://github.com/Ruby-Network/ruby/assets/101891804/be894ba4-27f0-4f3f-9a8c-8f5cafd185db)
* **What is the expected behavior?**
Go to website
Work

* **What is the motivation / use case for changing the behavior?**
IDK

* **Please tell us about your environment:**
  
  - Version: 2.0.0-beta.X
  - Browser: Chrome 118
  - Language: idk

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by MotorTruck1221** [comment]
That's a downtime issue that I'm hoping to fix in the next update. Please don't complain about downtime in the issues as it's not a bug.
