### ISSUE TITLE
Down in some areas or maybe everywhere

### ISSUE THREAD

**Issue by Briggan31** [Ruby-Network/ruby#30]
When I try to open the site it starts to load and then just stops after a while a cloadflare error shows up saying that I was connected to the internet and connected to the cloudflare server but that there was a host error on your end 
Error code is 522
![Screenshot_20240702_094219_Chrome](https://github.com/Ruby-Network/ruby/assets/174468546/925ed124-af9b-41af-8c83-81458d1ded39)

**Comment by Briggan31** [comment]
If you can fix it please do

**Comment by MotorTruck1221** [comment]
I have shut Ruby down for a few days while I switch servers. Please join our [Discord Server](https://dsc.gg/rubynetwork) to get updates as soon as they happen
